### ISSUE TITLE
State.run failing on State instances 

### ISSUE THREAD

**Issue by b-gran** [mattbierner/akh#32]
When using the prototype form of `State.run`: `State.prototype.run` (e.g. `State.of('something').run('whatever')`), the operation fails with a cryptic error message: 

```
TypeError: k is not a function
 at Object.f (node_modules/akh.codensity/trans/codensity.js:24:32)
      at Object.module.exports.tail.module.exports.trampoline.f [as trampoline] (node_modules/akh.codensity/node_modules/akh.core.trampoline/index.js:21:23)
      at Function.spec.Monad.spec.Monoid.spec.Transformer.CodensityT.run (node_modules/akh.codensity/trans/codensity.js:60:11)
      at spec.Monad.spec.Monoid.spec.Transformer.Instance.run (node_modules/akh.codensity/trans/codensity.js:47:27)
      at Context.<anonymous> (tests/state.js:21:15)
```

`State.prototype.run` works fine when used from `akh.state` directly.

See PR #33 for a failing test

Verified the issues exists for the following node versions:

```
0.12
4.0.0
4.8.4
8.0.0
8.2.1
```

**Comment by mattbierner** [comment]
Thanks. I believe the root cause of this was an old version of the State package getting getting picked up. I just published 3.1.2 which should fix this
